"use client";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export default function NewFAQ() {
  const faqs = [
    {
      question: "How does EasyWrite's AI work?",
      answer:
        "EasyWrite uses advanced natural language processing and machine learning models to understand your topic and generate high-quality, contextually relevant content. Our AI is trained on millions of articles and continuously learns to improve its output.",
    },
    {
      question: "Is the content original and plagiarism-free?",
      answer:
        "Yes! All content generated by EasyWrite is 100% original. Our AI creates unique content from scratch based on your inputs. We also include a built-in plagiarism checker to ensure your content is completely original before publishing.",
    },
    {
      question: "Can I edit the AI-generated content?",
      answer:
        "Absolutely! EasyWrite provides a full-featured editor where you can refine, edit, and customize the AI-generated content to match your voice and style. You have complete control over the final output.",
    },
    {
      question: "What types of content can I create?",
      answer:
        "You can create blog posts, articles, social media content, product descriptions, email newsletters, landing pages, and much more. We offer dozens of templates for different content types and use cases.",
    },
    {
      question: "Do I need technical skills to use EasyWrite?",
      answer:
        "Not at all! EasyWrite is designed to be user-friendly and intuitive. If you can type and click, you can use EasyWrite. No coding or technical knowledge required.",
    },
    {
      question: "How does pricing work?",
      answer:
        "We offer flexible pricing plans based on your needs. Start with our free plan to try out the platform, then upgrade to a paid plan for more features and higher usage limits. All plans include access to our core AI writing features.",
    },
    {
      question: "Can I cancel my subscription anytime?",
      answer:
        "Yes, you can cancel your subscription at any time with no penalties or fees. Your access will continue until the end of your current billing period.",
    },
    {
      question: "Is my data secure?",
      answer:
        "Security is our top priority. We use industry-standard encryption to protect your data, and we never share your content with third parties. Your content belongs to you, always.",
    },
  ];

  return (
    <section id="faq" className="w-full py-20 md:py-32">
      <div className="container mx-auto px-4 max-w-4xl">
        <div className="text-center mb-16 animate-fade-in">
          <h2 className="text-4xl md:text-5xl font-bold text-foreground font-poppins mb-4">
            Frequently Asked{" "}
            <span className="text-[var(--green-primary)]">Questions</span>
          </h2>
          <p className="text-lg text-muted-foreground font-inter">
            Everything you need to know about EasyWrite
          </p>
        </div>

        <div className="animate-fade-in-up">
          <Accordion type="single" collapsible className="w-full space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem
                key={index}
                value={`item-${index}`}
                className="bg-white shadow-card hover:shadow-card-hover transition-all duration-300 rounded-xl border border-border/50 px-6 data-[state=open]:shadow-card-hover"
              >
                <AccordionTrigger className="text-left font-semibold text-foreground hover:text-[var(--green-primary)] transition-colors font-poppins py-6 hover:no-underline">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground leading-relaxed font-inter pb-6">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>

        <div className="mt-12 text-center animate-fade-in">
          <p className="text-muted-foreground font-inter">
            Still have questions?{" "}
            <a
              href="mailto:support@easywrite.com"
              className="text-[var(--green-primary)] hover:text-[var(--green-dark)] font-semibold transition-colors"
            >
              Contact our support team
            </a>
          </p>
        </div>
      </div>
    </section>
  );
}
